// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epdaztavtnizvjxklxub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZGF6dGF2dG5penZqeGtseHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDc1NzcsImV4cCI6MjA3MTQyMzU3N30.oy3am91AFpqc1tm3XL9p90Au2DandC-NrTrjKL6Xipw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-application-name': 'rig-inspect-ui',
    },
  },
});